### ISSUE TITLE
Feature request: implementation of Parafac2

### ISSUE THREAD

**Issue by wdeback** [tensorly/tensorly#104]
I'd like to put in a request (similar to #5) for support for `PARAFAC2`, to handle irregular tensors with different sizes in one mode and shifts in dynamics.

I assume this has been on the to-do list, as you wrote in the "conclusion and future work" section of [your 2016 paper on `tensorly`](https://www.doc.ic.ac.uk/~ipanagak/pub/conf/C27.pdf): 

> "Going forward we will further extend the available decompositions with other state-of-the-art methods such as PARAFAC2 [...]".

In my specific application (cell shape dynamics), I have spatio-temporal data with different lengths for each sample (i.e. time between two cell divisions), and possible time shifts between the dynamics in the samples. 

Here are some related references and links:

Original paper: 
- Harshman, R.A., 1972. [PARAFAC2: Mathematical and technical notes](https://pdfs.semanticscholar.org/95ab/15398e144b6cc96b7967090742df421f0334.pdf). UCLA working papers in phonetics, 22(3044), p.122215. 

Algorithm and application:  
- Kiers, H.A., Ten Berge, J.M. and Bro, R., 1999. [PARAFAC2—Part I. A direct fitting algorithm for the PARAFAC2 model](https://www.researchgate.net/publication/230554388_PARAFAC2-Part_I_A_direct_fitting_algorithm_for_the_PARAFAC2_model). Journal of Chemometrics: A Journal of the Chemometrics Society, 13(3‐4), pp.275-294.
- Bro, R., Andersson, C.A. and Kiers, H.A., 1999. [PARAFAC2—Part II. Modeling chromatographic data with retention time shifts](https://materials.dagstuhl.de/files/16/16152/16152.RasmusBro.Preprint2.pdf). Journal of Chemometrics: A Journal of the Chemometrics Society, 13(3‐4), pp.295-309.

Implementations:
- MatLab (by Rasmus Bro): https://www.mathworks.com/matlabcentral/fileexchange/1089-parafac2
- R (by Nathaniel Helwig): https://www.rdocumentation.org/packages/multiway/versions/1.0-2/topics/parafac2
- Python/numpy (by Yun-Jhong Wu): https://github.com/yunjhongwu/matrix-routines/blob/master/parafac2.py

If you have some pointers how to approach this implementation within tensorly, I am happy to have a go at it.

**Comment by JeanKossaifi** [comment]
Hi @wdeback,

Indeed I want to have more decompositions in TensorLy, including PARAFAC2.

It should be fairly easy to implement in TensorLy. The code is almost the same as it would be in NumPy.

You'd simply want to use functions from the backend so the algorithm works with any backend (e.g. numpy, pytorch, etc). In other words, use`tensorly.fun` instead of `numpy.fun`.
We also implement svd, khatri-rao, etc.

You can have a look at the main parafac as an example. Happy to help if you want to have a go at it!

**Comment by MarieRoald** [comment]
@yngvem and I have implemented PARAFAC2 in TensorLy, following the ALS algorithm in (Kiers et al. 1999) and the MATLAB implementation by Rasmus Bro. However, we are not ready for a pull request yet since we need more docstrings.

If you are interested, then you can check out the PARAFAC2 branch in my fork of TensorLy ([link](https://github.com/MarieRoald/tensorly/tree/parafac2)). We tried to mimic the TensorLy code style so we hope that it should be easy to understand for those familiar with the rest of the codebase.

**Comment by jaydeepborkar** [comment]
Hi @JeanKossaifi, 

Has this been already worked on successfully? Is there anything I can still contribute with for adding any support for `PARAFAC2`? :)

**Comment by EverLookNeverSee** [comment]
Hi @JeanKossaifi i, I would like to work on other decomposition methods such as PARAFAC2.

**Comment by JeanKossaifi** [comment]
@EverLookNeverSee, @jaydeepborkar feel free to have a try!
@MarieRoald I guess the best would be to use your fork as a starting point?

**Comment by MarieRoald** [comment]
Hi, 

Our fork contains a fully working and tested PARAFAC2 implementation (including some performance tricks from Bro's MATLAB implementation from the N-way toolbox). The only thing missing is documentation and checking that there are no merge conflicts with the current TensorLy branch. Unfortunately, we have both been overloaded with teaching and other research duties this semester which stopped us from being able to do this, but we were planning on picking up the thread mid-December.

@EverLookNeverSee and @jaydeepborkar are welcome to help out with the documentation, make it faster or write more tests. Additionally, one feature that is missing is support for initialisation with a kruskal tensor (this can be done with a QR decomposition). 

One note: The PARAFAC2 implementation has the first mode changing along the last mode, so the mathematical model is (A_k D_k B = X_k) instead of the second mode changing along the last mode (A D_k B_k = X_k). We chose to do it this way, differently from [Kiers et al. (1999)](https://onlinelibrary.wiley.com/doi/abs/10.1002/(SICI)1099-128X(199905/08)13:3/4%3C275::AID-CEM543%3E3.0.CO;2-B), after experiencing many issues with having uneven matrices along the second mode. Ordering it this way makes it very easy to switch between a third-order tensor and a stack of matrices stored as a list.

**Comment by JeanKossaifi** [comment]
Great, thanks @MarieRoald !

By the way, I saw you are working on creating Skikit-Learn-like classes for decompositions: it's something we have been working on for TensorLy, would be great to work on this together if you are interested.

**Comment by tomwenseleers** [comment]
Note that the latest PARAFAC2 implementation is https://link.springer.com/chapter/10.1007/978-3-319-93764-9_9, "Nonnegative PARAFAC2: A Flexible Coupling Approach" - this is the only implementation that I know of that truly allows nonnegativity constraints on all the modes... Might be worth checking out if you are thinking of adding PARAFAC2 ?

**Comment by MarieRoald** [comment]
Hi @ JeanKossaifi. That sounds interesting, we would be interested in working on that!

Thank you or the suggestion, @tomwenseleers. I have an implementation of flexible PARAFAC2 on my personal repository that I have tested a little. The model seems less stable than Kiers PARAFAC2 and requires tuning of hyperparameters, but if there is a lot of interest, I could finish the implementation and port it to Tensorly.

**Comment by tomwenseleers** [comment]
@MarieRoald That sounds very cool! I think it would definitely be of interest to the community to have both this flexible PARAFAC2 & Kiers PARAFAC2 available, so if you think you could port it to Tensorly that would be really great!!

**Comment by JeanKossaifi** [comment]
@tomwenseleers: PARAFAC2 was added in PR #150 by @MarieRoald and @yngvem 

The question now is whether @cohenjer's Nonnegative version be incorporated in the existing algo -- or if we should have a separate non-negative version.

**Comment by cohenjer** [comment]
Hey all,

About the flexible algorithm, we could definitively have it in tensorly. However, it does not solve exactly the Nonnegative Parafac2 problem but rather an approximate coupling version of it (the approximation can be made almost exact by tuning the hyperparameters, but still). We are working currently on an exact version of Nonnegative Parafac2 but that's not yet published.

We are also working on bringing more advanced optimization and also classes to tensorly (check the [tensoptly](https://cohenjer.gitlab.io/tensoptly-website/) project) so we will most likely incorporate Nonnegative Parafac2 as a part of that large tensorly update, if it ever happens.
