### ISSUE TITLE
Line Search

### ISSUE THREAD

**Issue by JeanKossaifi** [tensorly/tensorly#158]
It would be good to add enhanced Line Search [1], at least to CP, as proposed in #29.

[1] M. Rajih, et. al., "Enhanced Line Search: A Novel Method to Accelerate PARAFAC", SIAM J. Matrix Anal. Appl., Vol. 30, No. 3, pp. 1128-1147

**Comment by aarmey** [comment]
I've been playing around with implementing a basic line search (copying it from Bro's implementation). To do this, it would be helpful to refactor out the [reconstruction error calculations from CP](https://github.com/tensorly/tensorly/blob/master/tensorly/decomposition/candecomp_parafac.py#L251-L263). I think the only downside to this is [`mttkrp`](https://github.com/tensorly/tensorly/blob/master/tensorly/decomposition/candecomp_parafac.py#L237) will be recalculated rather than reused. I figure this added cost is acceptable? If so I'll file a PR.

**Comment by JeanKossaifi** [comment]
Added in #183
