### ISSUE TITLE
Sparse decompositions not available in version 0.4.5?

### ISSUE THREAD

**Issue by rutujagurav** [tensorly/tensorly#189]
I decided to try the sparse CP from contrib.sparse.decomposition but got ModuleNotFound error.

I am simply doing this - 
`import tensorly as tl`
`from tensorly.contrib.sparse.decomposition import parafac as parafac_sparse`
`num_components = 20`
`(weights, parafac_factors) = parafac_sparse(tl.tensor(T, dtype='float64'), rank=num_components)`

However I get an error - `ModuleNotFoundError: No module named 'sparse'`

Also when I try to set the backend to sparse it says it isn't available. 
`ValueError: Unknown backend name 'sparse', known backends are ['numpy', 'mxnet', 'pytorch', 'tensorflow', 'cupy']`

Also, since the documentation is scant, can someone provide a reproducible code for working with sparse tensors (either scipy's COO or CSR formats)? Am I supposed to set the backend to 'sparse' as well as use the model implementations from contrib.sparse.decomposition ?

Thanks in advance.

**Comment by JeanKossaifi** [comment]
Hi @rutujagurav,

Can you post a minimal snippet of code to reproduce your issue? Otherwise we cannot know what `T` is in your code.

We actually do have some doc for the sparse backend, but any improvement is welcome! 
- [User guide](http://tensorly.org/dev/user_guide/sparse_backend.html)
- [Notebooks](https://github.com/JeanKossaifi/tensorly-notebooks/tree/master/07_pydata_sparse_backend
)
- [Sparse parafac notebook](https://github.com/JeanKossaifi/tensorly-notebooks/blob/master/07_pydata_sparse_backend/sparse_parafac.ipynb
)

From looking at your error it seems that you do not have the pydata sparse library installed which is used in conjunction with the numpy backend for sparse operations. You will need to [install it](https://sparse.pydata.org/en/stable/install.html) first. You can then directly use methods from `tensorly.contrib.sparse.decomposition on any sparse tensors`, with the `numpy` backend.

**Comment by rutujagurav** [comment]
Oh, that makes sense. I went to this link for sparse backend documentation: [http://tensorly.org/stable/user_guide/sparse_backend.html](http://tensorly.org/stable/user_guide/sparse_backend.html) and got a 404 error. Sorry about that and thanks for all the helpful links.
