### ISSUE TITLE
Is initializing ALS with a tensor safe to use?

### ISSUE THREAD

**Issue by eurunuela** [tensorly/tensorly#266]
Hi!

Would it be okay to use [the “hidden” option to initialize ALS with a tensor](https://github.com/tensorly/tensorly/blob/23ba632c36c361c78e23d49f8080d748c8bde8e8/tensorly/decomposition/_cp.py#L75) since it appears it is still being tested?

Thanks!

**Comment by JeanKossaifi** [comment]
Hi @eurunuela, thanks for bringing this up. Yes it is absolutely okay to use and enables many cool applications!
In fact it absolutely should not be hidden, the documentation for CP needs to be updated (and probably a small unit-test should be added). Feel free to have a go at it, I'll add whenever I get a minute otherwise!

**Comment by eurunuela** [comment]
Thank you @JeanKossaifi , that's great to know!

Right now I am working on a version of coherence-constrained ALS. I will open a PR once I feel comfortable with the results I obtain if the tensorly community finds it interesting/useful.

**Comment by JeanKossaifi** [comment]
Thanks @eurunuela, looking forward to it!
We've documented the init option in the init function, and in the main CP at 2471ad2654e360f1ab08b7eb318f41f8fc49ba63.
