### ISSUE TITLE
Greedy alignment of CP decompositions 

### ISSUE THREAD

**Issue by JeanKossaifi** [tensorly/tensorly#316]
(aligning to factor matrices by greedily finding permutation to maximize objective)

**Comment by cohenjer** [comment]
A quick additional comment: the problem can be formulated as

Given two sets of matrices A_i and B_i, find the optimal permutation \Pi of columns of A_i such that \sum_i ||A_i\Pi - B_i ||^2 is minimal. This problem is in fact a linear assignement problem, which can be solved by the munkres algorithm (link).

I don’t think it is worth adding scipy as a dependency to get the munkres algorithm, but maybe there is a nice way to let people use this optimal assignment if they are willing to install scipy.optimize (i.e. with an optional argument — can we have optional dependencies)?

Otherwise, there are several greedy suboptimal methods available, one simple possibility being

    normalize each column of the factors A_i and B_i
    build stacked matrices U = [A_1; A_2;...] and V = [B_1; B_2; ...] (stacked vertically), compute the scalar products U^tV
    pick the most correlated pairs in decreasing order to build \Pi.
    This will work in all the cases where the permutation is obvious, but may not provide the best result when factors have correlated columns.

**Comment by cohenjer** [comment]
We now have optimal alignment since @MarieRoald's Parafac2 PR and @caglayantuna's factor plot PR. I think we can safely close.
