### ISSUE TITLE
Is there a method can add weight to tensor composition (urgency) ?

### ISSUE THREAD

**Issue by wanglu2014** [tensorly/tensorly#373]
I have read some papers on weighted tensor decomposition (such as http://proceedings.mlr.press/v84/gottesman18a.html). To add  prior knowledge in tensor composition, I plan to add weight to the most important features in knowledge. The deadline of this project is near, and the performance of my implementation for this idea is poor. Could you kindly suggest an implementation of weighted tensor decomposition?

**Comment by JeanKossaifi** [comment]
One way you can do this in TensorLy is to set `normalize_factors` to True, see the doc, http://tensorly.org/dev/modules/generated/tensorly.decomposition.CP.html#tensorly.decomposition.CP

Note that for the robust tensor power iterations this is by default, so you automatically get the weights: http://tensorly.org/dev/modules/generated/tensorly.decomposition.CPPower.html#tensorly.decomposition.CPPower

**Comment by wanglu2014** [comment]
> One way you can do this in TensorLy is to set `normalize_factors` to True, see the doc, http://tensorly.org/dev/modules/generated/tensorly.decomposition.CP.html#tensorly.decomposition.CP
> 
> Note that for the robust tensor power iterations this is by default, so you automatically get the weights: http://tensorly.org/dev/modules/generated/tensorly.decomposition.CPPower.html#tensorly.decomposition.CPPower

Thank you for your reply. Sorry to make you misunderstand my question. To add prior knowledge in tensor composition, I plan to add weight to the known important features. Is there some implementation to use?

**Comment by cohenjer** [comment]
If you want to have weighted least squares, this is not something currently supported in Tensorly sadly. It's actually something we could work on. Some papers have proposed ideas, but my best pick for reading about this issue is:
http://alexhwilliams.info/itsneuronalblog/2018/02/26/censored-lstsq/
(this deals with missing values but the strategy can be used to weight data as well)
But this means adding new things to tensorly. I am not aware of Python code shared by researchers to perform weighted parafac. 

There are existing matlab codes however using e.g. [tensor toolbox](https://www.tensortoolbox.org/) see cp_wopt

**Comment by wanglu2014** [comment]
Thank you for your timely reply!
