### ISSUE TITLE
Backend 1-Dimensional Output Inconsistency

### ISSUE THREAD

**Issue by cswiercz** [tensorly/tensorly#40]
The way different backends output certain 1-dimensional data is inconsistent. In particular, the `dot` operation under the MXNet backend outputs 1x1 tensor whereas under the Pytorch backend the output is a scalar.

```python
>>> import tensorly as T
>>> T.set_backend('mxnet')
Using mxnet backend.
>>> T.assert_equal(T.dot(T.tensor([1,0]), T.tensor([0,1])), 0.0)
AssertionError: 
Items are not equal:
 ACTUAL: 
[ 0.]
<NDArray 1 @cpu(0)>
 DESIRED: 0.0
>>> T.set_backend('pytorch')
Using pytorch backend.
>>> T.assert_equal(T.dot(T.tensor([1,0]), T.tensor([0,1])), 0.0)
```

The issue came up when writing tests which work across all backends. I can think of several solutions to this issue but they all have certain design implications which require @JeanKossaifi 's input. For example,
* **Modify MXNet's or Pytorch's `dot()` command.** - The downside is that one need to remember this design decision for all new operators.
* **Manually cast all output into tensors** - Force the user to always convert output to `T.tensor([scalar_output])`. However, this comes with its own issues since the MXNet case `scalar_output` is not actually scalar.
* **?**

**Comment by JeanKossaifi** [comment]
This is an issue with the (annoying) way MXNet (doesn't) handle rank-0 tensors and yes, it is a pain! Someone wrote a nice summary about it here: https://discuss.mxnet.io/t/rank-0-arrays-in-mxnet-aka-pi-is-wrong/108

This really needs to be fixed in MXNet and the best thing to do would be to push for this to happen really... In the meantime, I used an ugly hack (using the asscalar method) in norm, sum etc, for the MXNet backend. The case you mention should hopefully not arise often (as a temporary solution, we can deal with it using inner product rather than the dot product).
