### ISSUE TITLE
'orthogonalize' for non_negative_parafac?

### ISSUE THREAD

**Issue by mfriendly** [tensorly/tensorly#447]
I can't seem to find the option for non_negative parafac to orthogonalize factors.
is there option for this ?

**Comment by caglayantuna** [comment]
There is no 'orthogonalise' option for non negative parafac. This option has been added to cp decomposition in this [commit](https://github.com/tensorly/tensorly/commit/f8782f6b65158dd08fccd7e8f3bf61786f7f4c27) . Maybe, you can follow this commit if you would like to add this option to Tensorly for non negative parafac. 

By the way, orthogonalise is missing in the doc and should be added.

**Comment by cohenjer** [comment]
To complete this answer, orthogonal nonnegative CP is very special, since orthogonal nonnegative matrices in fact are matrices where columns have disjoint support. It calls for special optimization techniques, so I am not convinced that, if we implement such methods in tensorly, that would be through an option in nonnegative_parafac.

You may have a look at [this ref](https://arxiv.org/pdf/1201.0901.pdf) for orthogonal nonnegative matrix factorization.
