### ISSUE TITLE
fetch_indian_pines broken

### ISSUE THREAD

**Issue by JeanKossaifi** [tensorly/tensorly#465]
fetch_indian_pines (and therefore it's test) fail, e.g. https://github.com/tensorly/tensorly/actions/runs/3660881883/jobs/6198153331

This seems to be due to the server hosting the data not supporting Open SSL 3
https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled

# Todo
- [ ] Remove test skip when fixed  #465

**Comment by JeanKossaifi** [comment]
Update: I cannot reproduce the issue locally, the fetching works fine for me

**Comment by cohenjer** [comment]
I will try to fix that asap.

**Comment by JeanKossaifi** [comment]
Thanks! If we get permission or if the license allows it we could also ship
the data directly in the repo given how small it is.

**Comment by cohenjer** [comment]
The data originally came from this website: [link](https://engineering.purdue.edu/~biehl/MultiSpec/hyperspectral.html)
It is stated that the data is free to use for research, but nothing about distribution. However the link on that page is dead (for a long time since it was dead already in 2018 when I looked). The data is now distributed by a third party university team [here](https://www.ehu.eus/ccwintco/index.php?title=Hyperspectral_Remote_Sensing_Scenes#Indian_Pines) without any license.

My guess is that we could include it in tensorly directly (6Mo).
