### ISSUE TITLE
How to use mps_decomposition?

### ISSUE THREAD

**Issue by Yolanpera** [tensorly/tensorly#92]
I mean I installed tensorly via pip,but I didn't know which pakage to import to use the matrix_product_state function.And I didn't find the manual in the website http://tensorly.org/stable/home.html.Can you help me?

**Comment by IlyaKisil** [comment]
Hi, @Yolanpera. It seems to me that the last update of `tensorly` on pypi.org was on the 8th of May 2018. Whereas module `mps_decomposition` was added sometime in July. So your best option would be to install from the source code available in this repository:
```
# clone the repository and cd into it
git clone https://github.com/tensorly/tensorly
cd tensorly

# Install it in your environment
pip install .
```
Then you could do something like
```python 
import numpy as np
import tensorly as tl
from tensorly.decomposition import matrix_product_state

tensor = tl.tensor(np.random.random((10,10,10)))

factors = matrix_product_state(tensor, rank=(1, 10, 10, 1))

tensor_rec = tl.mps_to_tensor(factors)
rec_error = tl.norm(tensor - tensor_rec, 2)/tl.norm(tensor)

print("="*20)
[print(f.shape) for f in factors]

print("="*20)
print(tensor_reconstructed.shape)

print("="*20)
print(rec_error)
```

As far as documentation is concerned, you have been looking at the pages related to the stable version. In order to see the most recent API reference, you need to open [http://tensorly.org/dev/](http://tensorly.org/dev/) instead.

**Comment by Yolanpera** [comment]
Hi,@IlyaKisil Thank you very much!
It works for me!

**Comment by JeanKossaifi** [comment]
I'll update the pypi version.

**Comment by JeanKossaifi** [comment]
Done - you can upgrade to 0.4.3 with pypi or conda.
